### ISSUE TITLE
please include a license

### ISSUE THREAD

**Issue by nvdk** [jackmatt2/ember-spring#1]
You seem to have done me a great service by figuring all this stuff out just before I needed it :). However before I reuse some of your code: under what license is it available?

**Comment by jackmatt2** [comment]
Yep, I can add one.  Can you suggest a good one that makes it available for commercial purposes but does not make me liable?

**Comment by jackmatt2** [comment]
I made it the MIT license.

**Comment by nvdk** [comment]
hey jack, I usually suggest apache2 or MIT. https://tldrlegal.com/ is a good resource if you want to dig a bit deeper.
